apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
  labels:
    app: hello-service
  annotations:
    gitops.example.com/managed-by: argocd
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: hello-service
  template:
    metadata:
      labels:
        app: hello-service
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: hello-service
          image: ghcr.io/soumendoluinit/myrepo@sha256:359e6a5b1e91bf78d3f872fa346b496d188365e2a771da3013dc395f7babe12e
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9080
              protocol: TCP

          env:
            - name: SERVER_PORT
              value: "9080"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/application1"

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 768Mi

          startupProbe:
            httpGet:
              path: /application1/getStudent
              port: 9080
            periodSeconds: 5
            failureThreshold: 12

          readinessProbe:
            httpGet:
              path: /application1/getStudent
              port: 9080
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /application1/getStudent
              port: 9080
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault